title: Lets Learn Python
lang: en
description: Lets learn trending technologies in a week ! and get crack technical interviews like having a piece of cake

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
