title: Lets Learn Python
lang: en
description: Most Practical Learning Solution

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - static_file
