title: Lets Learn Python
lang: en
description: Python beginner guide

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: false

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
